/**
 * Zen Garden activity dataset — used by OpenAI to select activities for the 18-week plan.
 * Source: Zen Garden activity dataset spreadsheet.
 */

export interface ZenGardenActivity {
  zone: 'BALANCE' | 'BLOSSOM' | 'BLISS'
  activity: string
  corner: string
  benefits: string
  keyConcerns: string
}

export const ZEN_GARDEN_ACTIVITIES: ZenGardenActivity[] = [
  // =========================================================================
  // BALANCE ZONE
  // =========================================================================
  {
    zone: 'BALANCE',
    activity: 'Meditative Art (Shapes & Breath)',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Improves focus, Breath awareness improves attention, mind-body awareness, slows breathing',
    keyConcerns: 'Distraction, scattered mind, poor focus, disconnect from body, rapid/shallow breathing, anxiety, inability to slow down',
  },
  {
    zone: 'BALANCE',
    activity: 'Zen Doodling',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Gentle concentration, quiet mind. Calms mental activity and supports effortless focus',
    keyConcerns: 'Overthinking, mental clutter, racing thoughts, restlessness, inability to relax, constant mental noise',
  },
  {
    zone: 'BALANCE',
    activity: 'Zentangle',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Enhances brain integration, emotional processing, and mindful creative flow',
    keyConcerns: 'Overthinking, mental chaos, emotional overwhelm, lack of control, suppressed emotions, difficulty focusing, feeling stuck in repetitive thought patterns, inner confusion, lack of creative expression',
  },
  {
    zone: 'BALANCE',
    activity: 'Neurological Art',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Bilateral integration, mental balance. Supports brain integration and emotional regulation',
    keyConcerns: 'Mental imbalance, emotional instability, confusion, cognitive fatigue, lack of coordination, feeling mentally scattered',
  },
  {
    zone: 'BALANCE',
    activity: 'Sacred Geometry Mandala Coloring',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Structured calm, order restoration, Creative activation. Restores inner order and promotes calm focus',
    keyConcerns: 'Chaos, anxiety, lack of structure, mental overwhelm, need for control, difficulty organizing thoughts',
  },
  {
    zone: 'BALANCE',
    activity: 'Stone Balancing',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Patience, grounded focus. Develops patience and deep grounding',
    keyConcerns: 'Impatience, urge for quick results, frustration when things don\'t work, inability to slow down, feeling scattered, lack of stability, difficulty staying present, inner restlessness',
  },
  {
    zone: 'BALANCE',
    activity: 'Object Painting',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Encourages mindful creativity and present-moment engagement',
    keyConcerns: 'Creative blocks, boredom, lack of presence, suppressed expression',
  },
  {
    zone: 'BALANCE',
    activity: 'Clay Modelling',
    corner: 'Creative Mindfulness Corner',
    benefits: 'Supports emotional release and tactile grounding',
    keyConcerns: 'Stress, emotional buildup, inner tension, need for grounding',
  },
  {
    zone: 'BALANCE',
    activity: 'Box Breathing',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Calms stress and restores focus',
    keyConcerns: 'Overthinking, stress, lack of focus, mental clutter',
  },
  {
    zone: 'BALANCE',
    activity: '4-7-8 Breathing',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Reduces anxiety and promotes relaxation',
    keyConcerns: 'Anxiety, racing thoughts, poor sleep, restlessness',
  },
  {
    zone: 'BALANCE',
    activity: 'Resonance Frequency Breathing',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Balances heart rate and nervous system',
    keyConcerns: 'Stress, irregular heartbeat, nervous system imbalance, anxiety',
  },
  {
    zone: 'BALANCE',
    activity: 'Creative Energy Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Stimulates creativity and mental flow',
    keyConcerns: 'Creative blocks, lack of ideas, brain fog, low inspiration',
  },
  {
    zone: 'BALANCE',
    activity: 'Energizing Morning Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Boosts energy and alertness',
    keyConcerns: 'Low energy, fatigue, sluggishness, lack of alertness',
  },
  {
    zone: 'BALANCE',
    activity: 'Vagus Nerve Reset Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Activates relaxation and nervous system balance',
    keyConcerns: 'Anxiety, panic response, emotional overwhelm, stress sensitivity',
  },
  {
    zone: 'BALANCE',
    activity: 'Nervous System Regulation Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Reduces stress and stabilizes mood',
    keyConcerns: 'Mood swings, chronic stress, emotional instability, burnout',
  },
  {
    zone: 'BALANCE',
    activity: 'Quick Morning Energy Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Increases vitality and focus',
    keyConcerns: 'Morning fatigue, low motivation, lack of focus, laziness',
  },
  {
    zone: 'BALANCE',
    activity: 'Ocean Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Calms the mind and deepens breathing',
    keyConcerns: 'Restlessness, shallow breathing, mental noise, tension',
  },
  {
    zone: 'BALANCE',
    activity: 'Quiet Your Mind Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Reduces mental chatter and promotes calm',
    keyConcerns: 'Overthinking, racing thoughts, inability to relax, mental clutter',
  },
  {
    zone: 'BALANCE',
    activity: 'Energy Boost Natural High Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Increases oxygen and natural energy',
    keyConcerns: 'Low energy, burnout, sluggish body, lack of vitality',
  },
  {
    zone: 'BALANCE',
    activity: 'Kapalbhati Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Clears mental fog, energizes body and mind',
    keyConcerns: 'Brain fog, low energy, poor digestion, lack of clarity',
  },
  {
    zone: 'BALANCE',
    activity: 'Bhastrika Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Increases oxygen flow and revitalizes energy',
    keyConcerns: 'Fatigue, low stamina, dullness, low oxygen levels',
  },
  {
    zone: 'BALANCE',
    activity: 'Surya Vilom Anulom Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Activates the body and boosts vitality',
    keyConcerns: 'Low confidence, inactivity, sluggishness, lack of drive',
  },
  {
    zone: 'BALANCE',
    activity: 'Chandra Vilom Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Calms the mind and cools emotional agitation',
    keyConcerns: 'Anger, irritability, anxiety, emotional heat',
  },
  {
    zone: 'BALANCE',
    activity: 'Cooling Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Reduces heat, anger, and irritability',
    keyConcerns: 'Anger issues, frustration, irritability, body heat imbalance',
  },
  {
    zone: 'BALANCE',
    activity: 'Breathing to Destress Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Relaxes the nervous system and reduces stress',
    keyConcerns: 'Stress, overwhelm, tension, nervous exhaustion',
  },
  {
    zone: 'BALANCE',
    activity: 'Sahaja Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Encourages natural calm and gentle breath regulation',
    keyConcerns: 'Restlessness, imbalance, inability to relax, inner unease',
  },
  {
    zone: 'BALANCE',
    activity: '7 Chakra - Grounding Frequency – Root (396 Hz)',
    corner: 'Frequency Alignment Corner',
    benefits: 'Promotes grounding and emotional stability',
    keyConcerns: 'Fear, insecurity, lack of grounding, instability',
  },
  {
    zone: 'BALANCE',
    activity: '7 Chakra - Flow Frequency – Sacral (417 Hz)',
    corner: 'Frequency Alignment Corner',
    benefits: 'Supports emotional flow and creativity',
    keyConcerns: 'Creative blocks, emotional suppression, low pleasure, lack of flow',
  },
  {
    zone: 'BALANCE',
    activity: '7 Chakra - Empowerment Frequency – Solar Plexus (528 Hz)',
    corner: 'Frequency Alignment Corner',
    benefits: 'Builds confidence and personal strength',
    keyConcerns: 'Low confidence, poor self-worth, lack of control, self-doubt',
  },
  {
    zone: 'BALANCE',
    activity: 'Brainwave - Alpha Frequency',
    corner: 'Frequency Alignment Corner',
    benefits: 'Promotes relaxation, calm focus, and stress reduction',
    keyConcerns: 'Stress, overthinking, lack of calm, poor focus',
  },
  {
    zone: 'BALANCE',
    activity: 'Brainwave - Beta Frequency',
    corner: 'Frequency Alignment Corner',
    benefits: 'Supports alertness, concentration, and active thinking',
    keyConcerns: 'Low alertness, poor concentration, mental dullness',
  },
  {
    zone: 'BALANCE',
    activity: 'Urdhva Prana Flow (Upward Expansion Flow)',
    corner: 'Marma Therapy Corner',
    benefits: 'Relieves mental overload, anxiety, emotional suppression, overthinking, lack of clarity, expression blocks',
    keyConcerns: 'Overthinking, anxiety, mental overload, expression block',
  },
  {
    zone: 'BALANCE',
    activity: 'Madhya Agni Flow (Core Regulation Flow)',
    corner: 'Marma Therapy Corner',
    benefits: 'Regulates anxiety stored in the gut, addresses control issues, fear, emotional heaviness, nervous system dysregulation',
    keyConcerns: 'Gut anxiety, control issues, fear, emotional heaviness, nervous imbalance',
  },
  {
    zone: 'BALANCE',
    activity: 'Adho Sthira Flow (Downward Grounding Flow)',
    corner: 'Marma Therapy Corner',
    benefits: 'Addresses feeling ungrounded, scattered, disconnected, fatigue, instability, lack of direction',
    keyConcerns: 'Feeling lost, ungrounded, instability, lack of direction, fatigue',
  },
  {
    zone: 'BALANCE',
    activity: 'Sound Healing Session (Bowls & Resonance)',
    corner: 'Sound Healing Corner',
    benefits: 'Induces deep relaxation and energetic balance',
    keyConcerns: 'Stress, anxiety, emotional heaviness, inner tension, mental overload, difficulty relaxing, sleep issues, feeling energetically drained',
  },

  // =========================================================================
  // BLOSSOM ZONE
  // =========================================================================
  {
    zone: 'BLOSSOM',
    activity: 'Emotional Reset Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Releases emotional tension and blockages',
    keyConcerns: 'Emotional buildup, stress, overwhelm, inner heaviness',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Dissolve Your Ego Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Reduces overthinking and emotional resistance',
    keyConcerns: 'Overthinking, control issues, emotional resistance, rigidity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Release Dopamine in 5 Mins Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Boosts mood and motivation',
    keyConcerns: 'Low mood, lack of motivation, dullness, no excitement',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Grief Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Supports deep emotional release and healing',
    keyConcerns: 'Grief, loss, sadness, emotional pain, fear of letting go',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Gratitude Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Cultivates appreciation and positive emotions',
    keyConcerns: 'Negativity, dissatisfaction, lack of appreciation, low positivity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Feel Safe in Your Body Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Builds emotional safety and grounding',
    keyConcerns: 'Anxiety, lack of safety, hypervigilance, body tension',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Nadi Shuddhi Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Balances emotional and mental states',
    keyConcerns: 'Emotional imbalance, stress, inner conflict, instability',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Brahmari Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Reduces anxiety and soothes emotional tension',
    keyConcerns: 'Anxiety, anger, emotional tension, restlessness',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Bandha Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Builds inner stability and emotional grounding',
    keyConcerns: 'Lack of control, instability, emotional weakness, insecurity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Vibahiha Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Supports emotional release and deep calming',
    keyConcerns: 'Emotional suppression, grief, need for release, heaviness',
  },
  {
    zone: 'BLOSSOM',
    activity: '7 Chakra - Harmony Frequency – Heart (639 Hz)',
    corner: 'Frequency Alignment Corner',
    benefits: 'Encourages emotional healing and connection',
    keyConcerns: 'Relationship pain, lack of love, emotional disconnection, loneliness',
  },
  {
    zone: 'BLOSSOM',
    activity: '7 Chakra - Expression Frequency – Throat (741 Hz)',
    corner: 'Frequency Alignment Corner',
    benefits: 'Supports clear communication and self-expression',
    keyConcerns: 'Communication issues, fear of expression, suppression, social anxiety',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Brainwave - Gamma Frequency',
    corner: 'Frequency Alignment Corner',
    benefits: 'Enhances insight, emotional integration, and higher awareness',
    keyConcerns: 'Emotional confusion, lack of clarity, low awareness, mental fog',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Emotional Freedom Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Process emotional blocks',
    keyConcerns: 'Emotional blocks, stuck feelings, inner heaviness, suppression',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Forgiveness & Letting Go Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Release resentment',
    keyConcerns: 'Resentment, anger, inability to forgive, emotional burden',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Inner Child Healing Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Heal early emotional wounds',
    keyConcerns: 'Childhood wounds, abandonment issues, insecurity, trauma',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Liberating Fear Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Releases fear and builds inner courage',
    keyConcerns: 'Fear, anxiety, insecurity, feeling stuck, avoidance',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Ho\'oponopono Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Supports forgiveness, healing, and emotional cleansing',
    keyConcerns: 'Guilt, resentment, relationship pain, inner conflicts, emotional burden, lack of closure',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Heartfulness Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Cultivates inner peace and emotional balance',
    keyConcerns: 'Stress, emotional instability, restlessness, lack of inner peace',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Self-Love Meditation',
    corner: 'Frequency Alignment Corner',
    benefits: 'Build inner acceptance',
    keyConcerns: 'Low self-worth, self-criticism, lack of acceptance, insecurity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Emotional Wheel & Body Mapping',
    corner: 'Self-Awareness Corner',
    benefits: 'Increase emotional literacy',
    keyConcerns: 'Emotional confusion, lack of self-awareness, identity issues, poor emotional understanding',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Tree of My Life Exploration',
    corner: 'Self-Awareness Corner',
    benefits: 'Identity reflection',
    keyConcerns: 'Identity confusion, lack of direction, self-doubt, unclear self-image',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Mask Activity',
    corner: 'Self-Awareness Corner',
    benefits: 'Explore hidden self vs projected identity',
    keyConcerns: 'Social masking, fear of judgment, identity confusion, lack of authenticity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Self Reflection Worksheet',
    corner: 'Self-Awareness Corner',
    benefits: 'Encourages structured self-awareness and clarity',
    keyConcerns: 'Overthinking, lack of clarity, confusion about self, mental clutter',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Emotional Wheel',
    corner: 'Self-Awareness Corner',
    benefits: 'Improves emotional awareness and labeling',
    keyConcerns: 'Difficulty identifying emotions, emotional confusion, poor emotional vocabulary, inner disconnect',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Self Reflection Cards',
    corner: 'Self-Awareness Corner',
    benefits: 'Promotes insight and self-discovery',
    keyConcerns: 'Lack of self-awareness, confusion, indecision, disconnection from inner thoughts',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Healing Johari Window',
    corner: 'Self-Awareness Corner',
    benefits: 'Self-perception vs others\' perception',
    keyConcerns: 'Blind spots, self-perception issues, lack of feedback awareness, identity conflict',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Creative Expression Studio (Draw, Shape, Journal)',
    corner: 'Self-Expression Corner',
    benefits: 'Express unspoken feelings',
    keyConcerns: 'Suppressed emotions, inability to express, bottled feelings, inner pressure',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Healing Jars (Anger, Fear, Guilt)',
    corner: 'Self-Expression Corner',
    benefits: 'Symbolic emotional release',
    keyConcerns: 'Anger, fear, guilt, emotional buildup, need for release',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Inner Child Creative Work',
    corner: 'Self-Expression Corner',
    benefits: 'Reconnect with younger self',
    keyConcerns: 'Inner child wounds, disconnection from self, unresolved emotions',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Anger Release Worksheet',
    corner: 'Self-Expression Corner',
    benefits: 'Provides structured outlet for processing anger',
    keyConcerns: 'Anger issues, suppressed anger, emotional buildup, frustration, difficulty expressing anger',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Journaling Practice',
    corner: 'Self-Expression Corner',
    benefits: 'Structured emotional processing',
    keyConcerns: 'Overthinking, emotional clutter, lack of clarity, mental overwhelm',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Healthy Boundaries Practice',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Assertiveness building',
    keyConcerns: 'Low confidence, poor boundaries, people-pleasing, fear of saying no',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Love Letter to Self',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Strengthen self-worth',
    keyConcerns: 'Low self-worth, self-doubt, lack of self-love, insecurity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Inner Critic vs Inner Coach',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Restructure self-talk',
    keyConcerns: 'Negative self-talk, inner criticism, lack of confidence, self-sabotage',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Find Your Wings to Fly',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Identifies strengths and builds self-belief',
    keyConcerns: 'Low confidence, self-doubt, lack of direction, feeling stuck, low self-worth',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Swish Technique',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Reduces negative patterns and shifts to positive thinking',
    keyConcerns: 'Negative thinking, limiting beliefs, self-sabotage, overthinking, lack of focus',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Appreciation Cards',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Building gratitude and appreciation for self and others through reflective prompts',
    keyConcerns: 'Negativity, lack of appreciation, low mood, emotional heaviness, dissatisfaction',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Self Love Cards',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Strengthening bond with self through reflective prompts',
    keyConcerns: 'Low self-worth, self-doubt, lack of self-love, insecurity, inner disconnect',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Book of Compassion',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Fostering compassion for self and others through note writing',
    keyConcerns: 'Harsh self-judgment, lack of empathy, guilt, emotional pain, relationship strain',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Affirmations Practice',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Reprogram self-beliefs',
    keyConcerns: 'Limiting beliefs, negative thinking, lack of confidence, self-doubt',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Gratitude / Compassion Cards',
    corner: 'Self-Love & Acceptance Corner',
    benefits: 'Increase positive focus',
    keyConcerns: 'Negativity, lack of gratitude, emotional heaviness, low positivity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Mirror of Truth Reflection',
    corner: 'Self Reflection and Self Talk',
    benefits: 'Honest self-confrontation',
    keyConcerns: 'Self-denial, avoidance, lack of honesty, inner confusion',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Gestalt Two Chairs',
    corner: 'Self Reflection and Self Talk',
    benefits: 'Resolve inner conflict',
    keyConcerns: 'Inner conflict, indecision, emotional struggle, lack of clarity',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Anger Release Experience',
    corner: 'Self Reflection and Self Talk',
    benefits: 'Safe emotional discharge',
    keyConcerns: 'Anger issues, suppressed anger, emotional buildup, frustration',
  },
  {
    zone: 'BLOSSOM',
    activity: 'Wisdom Corner',
    corner: 'Self Reflection and Self Talk',
    benefits: 'Access inner guidance',
    keyConcerns: 'Lack of direction, confusion, disconnection from inner voice, poor decision-making',
  },

  // =========================================================================
  // BLISS ZONE
  // =========================================================================
  {
    zone: 'BLISS',
    activity: 'Sufi Breathing',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Deepens spiritual awareness and connection',
    keyConcerns: 'Lack of meaning, disconnection, spiritual emptiness, inner void',
  },
  {
    zone: 'BLISS',
    activity: 'Meet Your Higher Self Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Access inner guidance and clarity',
    keyConcerns: 'Confusion, lack of direction, poor decision-making, disconnection from self',
  },
  {
    zone: 'BLISS',
    activity: '15 Min Chakra Activation Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Aligns and balances energy centers',
    keyConcerns: 'Energy imbalance, lack of alignment, inner blocks, disharmony',
  },
  {
    zone: 'BLISS',
    activity: 'Activate Pineal Gland Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Enhances intuition and awareness',
    keyConcerns: 'Low intuition, lack of clarity, overthinking, disconnection from insight',
  },
  {
    zone: 'BLISS',
    activity: 'Create Your New Reality Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Supports intention and manifestation',
    keyConcerns: 'Feeling stuck, lack of direction, limiting beliefs, low vision',
  },
  {
    zone: 'BLISS',
    activity: 'Manifest Abundance Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Aligns mindset with prosperity and possibility',
    keyConcerns: 'Money blocks, scarcity mindset, lack of growth, abundance issues',
  },
  {
    zone: 'BLISS',
    activity: 'Shamanic Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Induces deep trance and inner exploration',
    keyConcerns: 'Deep emotional blocks, subconscious patterns, unresolved trauma',
  },
  {
    zone: 'BLISS',
    activity: 'Enter the 9th Dimension Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Expands consciousness and perception',
    keyConcerns: 'Limited thinking, lack of expansion, rigid mindset, stagnation',
  },
  {
    zone: 'BLISS',
    activity: 'Breath of God Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Deepens divine connection and presence',
    keyConcerns: 'Spiritual disconnection, lack of faith, inner emptiness, void',
  },
  {
    zone: 'BLISS',
    activity: 'Quantum Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Accesses expanded states of awareness',
    keyConcerns: 'Feeling stuck, inability to shift perspective, mental rigidity',
  },
  {
    zone: 'BLISS',
    activity: 'Altered State of Consciousness Breathwork',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Shifts perception and deepens inner experience',
    keyConcerns: 'Need for breakthrough, deep transformation, stuck patterns',
  },
  {
    zone: 'BLISS',
    activity: 'Ujjayi Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Deepens concentration and meditative awareness',
    keyConcerns: 'Lack of focus, scattered mind, weak concentration, distraction',
  },
  {
    zone: 'BLISS',
    activity: 'Mindful Breathwork Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Cultivates presence and breath awareness',
    keyConcerns: 'Lack of presence, constant distraction, overthinking, mind wandering',
  },
  {
    zone: 'BLISS',
    activity: 'Sushumna Nadi Shuddhi Pranayama',
    corner: 'Conscious Breathwork Corner',
    benefits: 'Supports deep inner balance and meditative states',
    keyConcerns: 'Inner imbalance, lack of alignment, spiritual disconnection, instability',
  },
  {
    zone: 'BLISS',
    activity: '7 Chakra - Clarity Frequency – Third Eye (852 Hz)',
    corner: 'Frequency Alignment Corner',
    benefits: 'Enhances intuition and inner clarity',
    keyConcerns: 'Lack of intuition, confusion, poor clarity, overthinking',
  },
  {
    zone: 'BLISS',
    activity: '7 Chakra - Union with Higher Power – Crown (963 Hz) Frequency',
    corner: 'Frequency Alignment Corner',
    benefits: 'Deepens spiritual connection and awareness',
    keyConcerns: 'Disconnection from purpose, lack of higher connection, emptiness',
  },
  {
    zone: 'BLISS',
    activity: 'Brainwave - Theta Frequency',
    corner: 'Frequency Alignment Corner',
    benefits: 'Encourages emotional processing, creativity, and deep inner reflection',
    keyConcerns: 'Emotional blocks, lack of creativity, shallow thinking, stuck emotions',
  },
  {
    zone: 'BLISS',
    activity: 'Brainwave - Delta Frequency',
    corner: 'Frequency Alignment Corner',
    benefits: 'Supports deep meditation, restoration, and profound inner stillness',
    keyConcerns: 'Poor sleep, deep fatigue, lack of restoration, exhaustion',
  },
  {
    zone: 'BLISS',
    activity: 'Trataka (Candle Gazing)',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Improve focus, mental clarity',
    keyConcerns: 'Poor focus, distraction, weak concentration, mental clutter',
  },
  {
    zone: 'BLISS',
    activity: 'Soham Meditation',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Breath awareness, identity softening',
    keyConcerns: 'Identity confusion, overthinking, lack of self-awareness',
  },
  {
    zone: 'BLISS',
    activity: 'Manifestation / Meet Your Higher Self Meditation',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Future self integration',
    keyConcerns: 'Lack of direction, purpose confusion, disconnection from self',
  },
  {
    zone: 'BLISS',
    activity: '7 Chakra Alignment Meditation',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Energy balance',
    keyConcerns: 'Imbalance, lack of flow, internal disharmony',
  },
  {
    zone: 'BLISS',
    activity: 'Pyramid / Crystal Pod Meditation',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Amplify intention, stillness',
    keyConcerns: 'Lack of intention, scattered energy, lack of clarity',
  },
  {
    zone: 'BLISS',
    activity: 'Grounding Path Walk',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Embodied mindfulness',
    keyConcerns: 'Disconnection from body, stress, lack of presence',
  },
  {
    zone: 'BLISS',
    activity: 'Salt Cleansing Ritual',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Symbolic release',
    keyConcerns: 'Emotional heaviness, negativity, energetic burden',
  },
  {
    zone: 'BLISS',
    activity: 'Nature Mandala Ritual',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Grounding ritual',
    keyConcerns: 'Disconnection from nature, instability, lack of grounding',
  },
  {
    zone: 'BLISS',
    activity: 'Sand Garden Practice',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Impermanence awareness, grounding',
    keyConcerns: 'Attachment issues, lack of grounding, difficulty letting go',
  },
  {
    zone: 'BLISS',
    activity: 'Manifest Your Dreams Worksheet',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Conscious life direction',
    keyConcerns: 'Lack of clarity, no life direction, stagnation, low vision',
  },
  {
    zone: 'BLISS',
    activity: 'Write a Letter to the Universe Worksheet',
    corner: 'Meditation and Ritual Corner',
    benefits: 'Connecting with higher self, conscious life direction',
    keyConcerns: 'Emotional suppression, lack of trust, unclear desires, disconnection from higher self',
  },
]
